pipeline {
  agent any
  parameters {
    choice(
      name: 'RDS_REGION',
      choices: ['us-east-1', 'us-east-2', 'ap-southeast-1', 'ap-southeast-2'],
      description: 'Select the Region of RDS.'
    )

    extendedChoice(
      name: 'RDS_INSTANCE',
      description: 'Check the Instance you need to snapshot',
      multiSelectDelimiter: ',',
      type: 'PT_CHECKBOX',
      groovyScript: """
        return ['database-1','database-2','database-3']
      """
    )
  }

  environment {
    ASSUME_IAM_ROLE_NAME  = "rds-snapshot-iam-role"
  }

  stages {

    stage('Checkout SCM From the pipeline') {
      steps {
        cleanWs()
        checkout([$class: 'GitSCM', branches: [[name: 'main']],url: 'git@bitbucket.org:etsprojects/loans-sre-pipelines.git'])
      }
    }

    stage('RDS Snapshot') {
      steps {
        script {
          withAWS(credentials:'aws-credentials') {
            sh "echo rds database snapshot in progress please wait..."
            sh "python3 rds/snapshot.py --db_instances $RDS_INSTANCE --region $RDS_REGION"
          }
 
        }
      }
    }

    // Add more stages as needed
  }
}

